version: '3.7'

services:

  # client:
  #   build:
  #     context: ./services/client
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './services/clients:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - 3007:3000
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_EVS_SERVICE_URL=${REACT_APP_EVS_SERVICE_URL}
  #   depends_on:
  #     - evs

  evs:
    build:
      context: ./services/evs
      dockerfile: Dockerfile
    volumes:
      - './services/evs:/usr/src/app'
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@evs-db:5432/evs_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@evs-db:5432/evs_test
    depends_on:
      - evs-db

  evs-db:
    build:
      context: ./services/evs/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - evs
