version: '3.7'

services:

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_EVS_SERVICE_URL=${REACT_APP_EVS_SERVICE_URL}
    ports:
      - 3007:80
    depends_on:
      - evs

  evs:
    build:
      context: ./services/evs
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@evs-db:5432/evs_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@evs-db:5432/evs_test
    depends_on:
      - evs-db

  evs-db:
    build:
      context: ./services/evs/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - evs
      - frontend
