FROM node:11.12.0-alpine as builder

WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
COPY yarn.lock /usr/src/app/yarn.lock
RUN yarn
RUN yarn global add react-scripts@2.1.8 -g --silent

ARG REACT_APP_EVS_SERVICE_URL
ENV REACT_APP_EVS_SERVICE_URL = $REACT_APP_EVS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV = $NODE_ENV

COPY . /usr/src/app
RUN yarn run build

FROM nginx:1.15.9-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]